require 'rubygems'
require 'rake'

begin
  gem 'jeweler', '>= 0.11.0'
  require 'jeweler'
  Jeweler::Tasks.new do |s|
    s.name = "nate"
    s.summary = "A HTML templating engine that uses logicless and valueless templates."
    s.description = 'Description of Nate here'
    s.authors = [ 'Sean T Allen', 'James Ladd' ]
    s.homepage = 'http://github.com/jamesladd/nate/tree/master/ruby/'
    s.files.exclude 'features/'
    s.files.exclude 'spec/'
    s.add_dependency 'hpricot', '>= 0.8.2'
    s.add_development_dependency 'compass', '>= 0.10.5'
    s.add_development_dependency 'cucumber', '>= 0.9.0'
    s.add_development_dependency 'datamapper', '>= 1.0.0'
    s.add_development_dependency 'dm-sqlite-adapter', '>= 1.0.0'
    s.add_development_dependency 'haml', '>= 3.0.0'
    s.add_development_dependency 'jeweler', '>= 0.11.0'
    s.add_development_dependency 'lorax', '>= 0.2.0'
    s.add_development_dependency 'rails' '>- 3.0.0'
    s.add_development_dependency 'rake', '>= 0.8.7'
    s.add_development_dependency 'sinatra', '>= 1.0'
    s.add_development_dependency 'sanitize', '>= 1.2.1'
  end
rescue LoadError
  puts "Jeweler not available. Install it with: sudo gem install jeweler --version '>= 0.11.0'"
  exit(1)
end
