desc "Run ToDo application example using a layout template"
task :run_with_layout => [ :build ] do
  system "ruby todo-layout.rb"
end

desc "Run ToDo application example without layout template"
task :run_without_layout => [ :build ] do
  system "ruby todo-no-layout.rb"
end

desc "Build example"
task :build => [ :clean ] do
  system "compass compile"
end

desc "Cleanup example"
task :clean do
  system "rm -rf public/stylesheets/"
  system "rm -rf .sass_cache/"
end
